### ISSUE TITLE
Fuel Level Don't Sync through Players

### ISSUE THREAD

**Issue by amantu-qbit** [CQC-Scripting/cc-fuel#14]
If someone Refuels and someone else gets in a vehicle they don't seem to see the same fuel level. Like if someone drive and the fuel is empty and then someone else comes to the driving seat they'll be able to drive and they'll see the default fuel level. The same goes for Refueling.

**Comment by eoinmcbennett** [comment]
Hi, I think I know what’s causing the issue. I’ll try get a fix out ASAP. Unsure of the ETA currently. Thanks for flagging.

**Comment by amantu-qbit** [comment]
> Hi, I think I know what’s causing the issue. I’ll try get a fix out ASAP. Unsure of the ETA currently. Thanks for flagging.

I would Request you for pushing the fix early. My server is using your fuel script and it's now public and live. So we really need this fix

**Comment by Quinn101** [comment]
@amantu-qbit the dev branch currently has a fixed pushed to fix this issue. @eoinmcbennett is going to clean up it up slightly before pushing to the main branch. Let us know if this helps your problems

**Comment by amantu-qbit** [comment]
@Quinn101 Car from impound and Garage don't have any fuel

**Comment by eoinmcbennett** [comment]
> @Quinn101 Car from impound and Garage don't have any fuel

Check the exports in whatever script you use to impound / unimpound vehicles. cc-fuel does not deal with this directly

**Comment by amantu-qbit** [comment]
@eoinmcbennett It's an issue with cc-fuel. I changed to previous version and now it's working

**Comment by Maureks** [comment]
hey ! same issue with me , i've updated cc-fuel , the vehicleshop and the garage give cars with 0 fuel , it was working before the update

**Comment by eoinmcbennett** [comment]
Will be looking into this later today

**Comment by eoinmcbennett** [comment]
@amantu-qbit @Maureks Should be fixed now in the latest commits on deb

**Comment by Maureks** [comment]
Thanks ! Gonna give it a try !

**Comment by amantu-qbit** [comment]
@eoinmcbennett Having a new issue. Sometimes players can't target with a gas can in hand. Like it'll not target the vehicle. I got some bug reports from my live server players also I face it myself. But when I spawn any vehicle with admin power it'll always work. On the other hand. My own vehicle/ped vehicle will not work sometimes. IDk what's the issue.

**Comment by amantu-qbit** [comment]
Or maybe expand Targateable Bones? Not all car have same bones IG

**Comment by Maureks** [comment]
@amantu-qbit 
Do you have the qb-target default option for car interaction enabled? 

Just asking, because it used to happen to me, and when turned off it worked fine. But this was before the upgrade, I haven't tried it yet!

Thanks for the attention !

**Comment by amantu-qbit** [comment]
@Maureks Yup it's enabled

**Comment by amantu-qbit** [comment]
@Maureks Just Adding Bonnet/doors to cc fuel bones for testing

**Comment by amantu-qbit** [comment]
@Maureks Some car doesn't have those bone mentioned in cc-fuel config. Adding all doors and bonnet fixed it

**Comment by Maureks** [comment]
Oh cool ! thanks ! 
Can you give me just an example , I'm kinda new at this sorry !

Thanks in advance !

**Comment by eoinmcbennett** [comment]
Which car were you testing with and I will try find a fix

**Comment by amantu-qbit** [comment]
@eoinmcbennett I couldn't fix it with Kawasaki Ninja H2R. Except for this. I fixed for other cars.

**Comment by eoinmcbennett** [comment]
Fixed with #20
