### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by DevX32** [CQC-Scripting/cc-fuel#23]
there is no option to do siphon fuel

**Comment by NatasWillDoIt** [comment]
so i had this problem so what it did was added this to my  qb-target 

`Config.GlobalVehicleOptions = {
    options = {
                {
            type = "client",
            event = "inventory:client:ItemBox",
            icon = "fas fa-gas-pump",
            label = "Siphone Fuel",
	        item = "weapon_petrolcan",
        },
        {
            type = "client",
            event = "cc-fuel:client:siphonfuel",
            icon = "fas fa-gas-pump",
            label = "Siphone Fuel",
	    item = "mechanic_tools",
        },
    },
    distance = 2.5,
}`
